name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Update version in pyproject.toml
        run: |
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version ${{ github.event.inputs.version }}
          echo "TAG_NAME=v${{ github.event.inputs.version }}" >> $GITHUB_ENV
          uv sync

      - name: Archive Changelog
        uses: docker://ghcr.io/nonebot/auto-changelog:master
        with:
          archive_regex: '(?<=## )最近更新(?=\n)'
          archive_title: ${{ env.TAG_NAME }}
          commit_and_push: false

      - name: Push Tag
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m ":bookmark: Release ${{ env.TAG_NAME }}"
          git tag ${{ env.TAG_NAME }}
          git push && git push --tags
